dateModified: 1663957097
email:
  fromEmail: michael@bluth.com
  fromName: Pest
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5c7a8525-3882-4d34-91ab-89abbdc07046: 'Category Field' # Category Field
    7b6cb827-6ed5-400f-af34-3e5a5bdfac67: 'Assets Field' # Assets Field
    8a2fe4b1-2b76-4ab7-90fa-1ee6d7121033: Posts # Posts
    8aa25d25-894f-46dc-90ec-4321e430ed65: 'Date Field' # Date Field
    019d883f-364d-43a7-b347-86c72d16f5e6: 'Field Two' # Field Two
    023aa477-0702-4d32-a5fb-fc7aea994e88: 'Block Type One' # Block Type One
    28d665c1-92c8-4ead-8286-7eff290cfa63: 'Field Two' # Field Two
    152c19f5-57fb-4c10-bd2c-b9023096a694: Default # Default
    346e049c-33c4-4b90-815e-2431bc2dcbc6: 'Block Type Two' # Block Type Two
    657fe2c9-a6e2-4408-909e-5ef5b343e271: 'Field One' # Field One
    71730b1a-49d4-4e53-8f27-408897679aeb: 'Matrix Field' # Matrix Field
    73001bfc-68e5-4059-acf2-4ff4dba34359: 'Entries Field' # Entries Field
    954225e6-b357-4830-8024-1c9f8ba04ec6: 'Plain Text Field' # Plain Text Field
    b11e9b16-d6b0-4771-86bb-3fe962b4596d: Pest # Pest
    bda4d299-4f91-43c1-91d1-48abd1dd5fb4: Pest # Pest
    c100d296-028a-42e6-bfc7-77ff15eeae9a: 'Field One' # Field One
    ccc0d7c5-9563-4aa5-a5ac-7e9bfe333647: 'Dropdown Field' # Dropdown Field
    eabe62dd-b801-42c9-955a-8ee090206b50: 'Color Field' # Color Field
    f3d94bb4-a854-46a1-bd78-0a28ac91ec60: Common # Common
plugins:
  pest:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Pest
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
